INSERT INTO PUS_PERMISSION(ID, NAME)
VALUES (NEXT VALUE FOR SEQ_PERMISSION, 'ADMIN');

INSERT INTO PUS_ROLE(ID, NAME, DESCRIPTION)
VALUES (NEXT VALUE FOR SEQ_ROLE, 'ADMINISTRATOR', 'Administrator role');

INSERT INTO PUS_USER_ACCOUNT(ID, USERNAME, PASSWORD)
VALUES (NEXT VALUE FOR SEQ_USER_ACCOUNT, 'admin', 'admin');

INSERT INTO PUS_USER_ACCOUNT_ROLES(USER_ACCOUNT_ID, ROLE_ID)
VALUES (1, 1);

INSERT INTO PUS_ACCOUNT_ROLE_PERMISSIONS(ROLE_ID, PERMISSION_ID)
VALUES (1, 1);

